version: '3.9'

services:
  web:
    image: epo/web
    build: ./web
    container_name: web
    ports:
    - 8080:8080

  rest:
    container_name: rest
    image: epo/rest
    build: ./rest
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://psql_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - psql_db

  psql_db:
    container_name: psql_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
