#Docker-Compose ITA

version: '3.9'

services:
  web:
    image: epo/web
    build: ./web
    container_name: web-ita
    ports:
    - 8080:8080

  rest:
    image: epo/rest
    build: ./rest
    container_name: rest-ita
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://psql_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - psql_db

  psql_db:
    image: postgres
    container_name: psql_db-ita
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq-ita
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

  sender:
    image: epo/sender
    build: ./sender
    container_name: sender-ita
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq

  receiver:
    image: epo/receiver
    build: ./receiver
    container_name: receiver-ita
    ports:
      - "8083:8080"
    depends_on:
      - sender
      - rabbitmq

volumes:
  pgdata: {}
