#Docker-Compose ITA

version: '3.9'
name: epo-all
services:
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

networks:
  ita-network:
    external: true
  ger-network:
    external: true
  fra-network:
    external: true