#Docker-Compose ITA

version: '3.9'
name: epo-ita
services:
  
  web:
    image: epo/web
    build: ./web
    container_name: web-ita
    ports:
      - 8080:8080
    depends_on:
      - rest
    networks:
      - network-ita

  rest:
    image: epo/rest
    build: ./rest
    container_name: rest-ita
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://psql_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - psql_db
    networks:
      - network-ita

  psql_db:
    image: postgres
    container_name: psql_db-ita
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    #volumes:
    #  - pgdata:/var/lib/postgresql/data
    networks:
      - network-ita

  broadcast:
    image: epo/broadcast
    build: ./broadcast
    container_name: broadcast-ita
    environment:
      - spring_rabbitmq_host=rabbitmq
      - QUEUE_NAME=ita
      - REST_URL=http://rest:8080
      - LIST=ita,fra,ger
    ports:
      - "8082:8080"
    depends_on:
      - rest
    networks:
      - network-ita

networks:
  network-ita:
    name: rabbitmq-ita
    external: true

volumes:
  pgdata: {}
