version: "3"

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    ports:
    - 3307:3306
  web:
    image: "epo/web"
    ports:
    - "8080:8080"
  rest:
    image: "epo/rest"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/db_example?autoReconnect=true&useSSL=false
    ports:
    - "8081:8080"
    depends_on:
       - mysql