#Docker-Compose GER

version: '3.9'
name: epo-ger
services:
  web:
    image: epo/web
    build: ./web
    container_name: web-ger
    ports:
    - 8088:8080

  rest:
    image: epo/rest
    build: ./rest
    container_name: rest-ger
    ports:
      - 8089:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://psql_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - psql_db

  psql_db:
    image: postgres
    container_name: psql_db-ger
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  sender:
    image: epo/sender
    build: ./sender
    container_name: sender-ger
    environment:
      - spring_rabbitmq_host=rabbitmq
    ports:
      - "8090:8080"
    networks:
      - network1

  receiver:
    image: epo/receiver
    build: ./receiver
    container_name: receiver-ger
    ports:
      - "8091:8080"
    environment:
      - spring_rabbitmq_host=rabbitmq
      - QUEUE_NAME=ger
    depends_on:
      - sender
    networks:
      - network1

networks:
  network1:
    name: rabbitmq-ger
    external: true

volumes:
  pgdata: {}
