#Docker-Compose ITA

version: '3.9'

services:
  listener:
    image: epo/listener
    build: ./listener
    container_name: listener-ita2
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq-ita2
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

volumes:
  pgdata: {}
