#Docker-Compose GER

version: '3.9'
name: epo-ger
services:
  web:
    image: epo/web
    build: ./web
    container_name: web-ger
    ports:
    - 8088:8080
    networks:
      - network-ger
    environment:
      - REST_URL=http://rest:8080
      - NATION=DE

  rest:
    image: epo/rest
    build: ./rest
    container_name: rest-ger
    ports:
      - 8089:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://psql_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - psql_db
    networks:
      - network-ger

  psql_db:
    image: postgres
    container_name: psql_db-ger
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    #volumes:
    #  - pgdata:/var/lib/postgresql/data
    networks:
      - network-ger  

  broadcast:
    image: epo/broadcast
    build: ./broadcast
    container_name: broadcast-ger
    environment:
      - spring_rabbitmq_host=rabbitmq
      - QUEUE_NAME=ger
      - REST_URL=http://rest:8080
      - LIST_NATIONS=ita,fra,ger
      - POPULATION=3
    depends_on:
      - rest
    ports:
      - "8090:8080"
    networks:
      - network-ger

networks:
  network-ger:
    name: rabbitmq-ger
    external: true

volumes:
  pgdata: {}
