#Docker-Compose FRA

version: '3.9'
name: epo-fra
services:
  web:
    image: epo/web
    build: ./web
    container_name: web-fra
    ports:
    - 8084:8080
    networks:
      - fra-network

  rest:
    image: epo/rest
    build: ./rest
    container_name: rest-fra
    ports:
      - 8085:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://psql_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - psql_db
    networks:
      - fra-network

  psql_db:
    image: postgres
    container_name: psql_db-fra
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fra-network

  sender:
    image: epo/sender
    build: ./sender
    container_name: sender-fra
    ports:
      - "8086:8080"
    networks:
      - fra-network

  receiver:
    image: epo/receiver
    build: ./receiver
    container_name: receiver-fra
    ports:
      - "8087:8080"
    networks:
      - fra-network

networks:
  fra-network:
    name: fra-network
    external: false

volumes:
  pgdata: {}
