#Docker-Compose RABBIT_MQ

version: '3.9'
name: epo-all
services:
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network1
      - network2
      - network3

networks:
  network1:
      name : rabbitmq-ita
  network2:
      name : rabbitmq-fra
  network3:
      name : rabbitmq-ger