#Docker-Compose GER

version: '3.9'

services:
  web:
    image: epo/web
    build: ./web
    container_name: web-ger
    ports:
    - 8088:8080

  rest:
    image: epo/rest
    build: ./rest
    container_name: rest-ger
    ports:
      - 8089:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://psql_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - psql_db

  psql_db:
    image: postgres
    container_name: psql_db-ger
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq-ger
    image: rabbitmq:3-management
    ports:
      - "5675:5672"
      - "15675:15672"

  sender:
    image: epo/sender
    build: ./sender
    container_name: sender-ger
    ports:
      - "9000:8080"
    depends_on:
      - rabbitmq

  receiver:
    image: epo/receiver
    build: ./receiver
    container_name: receiver-ger
    ports:
      - "9001:8080"
    depends_on:
      - sender
      - rabbitmq

volumes:
  pgdata: {}
