spring:
    rabbitmq:
        host: localhost
        port: 5673
    multirabbitmq:
        enabled: true
        connections:
            connectionNameA:
                host: localhost
                port: 5680
            connectionNameB:
                host: localhost
                port: 5681